<a href="https://colab.research.google.com/github/lokesharora2000/Lokesh/blob/master/Movie_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

import tensorflow as tf
import tensorflow_datasets as tfds 
import tensorflow_hub as hub 



In [0]:
train_data, validation_data, test_data = tfds.load(
    name="imdb_reviews", 
    split=('train[:60%]', 'train[60%:]', 'test'),
    as_supervised=True)

In [0]:
tf.__version__

In [0]:
train_data_batch,train_label_batch=next(iter(train_data.batch(10)))

In [0]:
%tensorflow_version 2.x

In [34]:
train_data_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [35]:
train_label_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

In [0]:
pretrained_model="https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer= hub.KerasLayer(pretrained_model,input_shape=[],dtype=tf.string,trainable=True) 

In [42]:
model=tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense (Dense)                (None, 16)                336       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [0]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [59]:
history = model.fit(train_data.shuffle(10000).batch(512),
                    epochs=20,
                    validation_data=validation_data.batch(512),
                    verbose=1)

Epoch 1/20
30/30 [==============================] - 5s 181ms/step - loss: 0.7280 - accuracy: 0.5055 - val_loss: 0.6858 - val_accuracy: 0.5656
Epoch 2/20
30/30 [==============================] - 5s 156ms/step - loss: 0.6493 - accuracy: 0.6189 - val_loss: 0.6253 - val_accuracy: 0.6532
Epoch 3/20
30/30 [==============================] - 5s 164ms/step - loss: 0.5949 - accuracy: 0.6838 - val_loss: 0.5782 - val_accuracy: 0.7074
Epoch 4/20
30/30 [==============================] - 5s 158ms/step - loss: 0.5454 - accuracy: 0.7337 - val_loss: 0.5332 - val_accuracy: 0.7440
Epoch 5/20
30/30 [==============================] - 5s 150ms/step - loss: 0.4984 - accuracy: 0.7731 - val_loss: 0.4962 - val_accuracy: 0.7684
Epoch 6/20
30/30 [==============================] - 5s 155ms/step - loss: 0.4556 - accuracy: 0.8041 - val_loss: 0.4602 - val_accuracy: 0.7913
Epoch 7/20
30/30 [==============================] - 5s 162ms/step - loss: 0.4159 - accuracy: 0.8274 - val_loss: 0.4307 - val_accuracy: 0.8112
Epoch 

In [62]:
model.predict(["This is worst movie "])

array([[0.04922364]], dtype=float32)

In [66]:
results = model.evaluate(test_data.batch(512), verbose=2)

for name, value in zip(model.metrics_names, results):
  print("%s: %.3f" % (name, value))


loss: 0.323
accuracy: 0.863
